/*
 * sfsc_states.h
 *
 *  Created on: 28.10.2020
 *      Author: Eric
 */

#ifndef SRC_SFSC_ADAPTER_SFSC_STATES_H_
#define SRC_SFSC_ADAPTER_SFSC_STATES_H_

#ifdef __cplusplus
extern "C" {
#endif

#define SFSC_STATE_NONE 0
#define SFSC_STATE_BOOTSTRAP_CONNECTING 1
#define SFSC_STATE_BOOTSTRAP_SUBSCRIBED 2
#define SFSC_STATE_BOOTSTRAP_SUBSCRIBED_DISCARD_NEXT 3
#define SFSC_STATE_BOOTSTRAP_RECEIVEING 4
#define SFSC_STATE_SETUP 5
#define SFSC_STATE_SETUP_CONNECTING 6
#define SFSC_STATE_SETUP_AWAIT_WELCOME 7
#define SFSC_STATE_SETUP_RECEIVE_WELCOME 8
#define SFSC_STATE_OPERATIONAL 9
#define SFSC_STATE_EXPECT_HEARTBEAT 10
#define SFSC_STATE_EXPECT_QUERY_RESULT 11
#define SFSC_STATE_EXPECT_COMMAND_RESULT 12

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* SRC_SFSC_ADAPTER_SFSC_STATES_H_ */
