/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "generated.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(sfsc_BootstrapMessage, sfsc_BootstrapMessage, AUTO)


PB_BIND(sfsc_CommandRequest, sfsc_CommandRequest, 2)


PB_BIND(sfsc_CommandReply, sfsc_CommandReply, AUTO)


PB_BIND(sfsc_QueryRequest, sfsc_QueryRequest, AUTO)


PB_BIND(sfsc_QueryReply, sfsc_QueryReply, 2)


PB_BIND(sfsc_QueryReply_Expired, sfsc_QueryReply_Expired, AUTO)


PB_BIND(sfsc_QueryReply_Future, sfsc_QueryReply_Future, AUTO)


PB_BIND(sfsc_Hello, sfsc_Hello, AUTO)


PB_BIND(sfsc_Welcome, sfsc_Welcome, AUTO)


PB_BIND(sfsc_HeartbeatMessage, sfsc_HeartbeatMessage, AUTO)


PB_BIND(sfsc_SfscServiceDescriptor, sfsc_SfscServiceDescriptor, AUTO)


PB_BIND(sfsc_SfscServiceDescriptor_CustomTagsEntry, sfsc_SfscServiceDescriptor_CustomTagsEntry, AUTO)


PB_BIND(sfsc_SfscServiceDescriptor_ServiceTags, sfsc_SfscServiceDescriptor_ServiceTags, AUTO)


PB_BIND(sfsc_SfscServiceDescriptor_ServiceTags_PublisherTags, sfsc_SfscServiceDescriptor_ServiceTags_PublisherTags, AUTO)


PB_BIND(sfsc_SfscServiceDescriptor_ServiceTags_ServerTags, sfsc_SfscServiceDescriptor_ServiceTags_ServerTags, AUTO)


PB_BIND(sfsc_SfscServiceDescriptor_ServiceTags_ServerTags_RegexDefinition_VarRegex, sfsc_SfscServiceDescriptor_ServiceTags_ServerTags_RegexDefinition_VarRegex, AUTO)


PB_BIND(sfsc_SfscServiceDescriptor_ServiceTags_ServerTags_RegexDefinition_VarRegex_StringRegex, sfsc_SfscServiceDescriptor_ServiceTags_ServerTags_RegexDefinition_VarRegex_StringRegex, AUTO)


PB_BIND(sfsc_SfscServiceDescriptor_ServiceTags_ServerTags_RegexDefinition_VarRegex_NumberRegex, sfsc_SfscServiceDescriptor_ServiceTags_ServerTags_RegexDefinition_VarRegex_NumberRegex, AUTO)


PB_BIND(sfsc_SfscServiceDescriptor_ServiceTags_ServerTags_AckSettings, sfsc_SfscServiceDescriptor_ServiceTags_ServerTags_AckSettings, AUTO)


PB_BIND(sfsc_RequestOrAcknowledge, sfsc_RequestOrAcknowledge, AUTO)


PB_BIND(sfsc_RequestOrAcknowledge_Request, sfsc_RequestOrAcknowledge_Request, AUTO)


PB_BIND(sfsc_RequestOrAcknowledge_Acknowledge, sfsc_RequestOrAcknowledge_Acknowledge, AUTO)


PB_BIND(sfsc_Reply, sfsc_Reply, AUTO)


PB_BIND(sfsc_ChannelFactoryRequest, sfsc_ChannelFactoryRequest, AUTO)


PB_BIND(sfsc_ChannelFactoryReply, sfsc_ChannelFactoryReply, AUTO)


PB_BIND(sfsc_SfscId, sfsc_SfscId, AUTO)


PB_BIND(sfsc_Topic, sfsc_Topic, AUTO)


PB_BIND(sfsc_MessageType, sfsc_MessageType, AUTO)


PB_BIND(sfsc_RequestPattern, sfsc_RequestPattern, AUTO)


PB_BIND(sfsc_ReplyPattern, sfsc_ReplyPattern, AUTO)


PB_BIND(sfsc_RegistryEntry, sfsc_RegistryEntry, 2)



