/*
 * zmtp_states.h
 *
 *  Created on: 29.10.2020
 *      Author: Eric
 */

#ifndef SRC_ZMTP_ZMTP_STATES_H_
#define SRC_ZMTP_ZMTP_STATES_H_


#ifdef __cplusplus
extern "C" {
#endif


#define ZMTP_STATE_NONE 0
#define ZMTP_STATE_GREETING 1
#define ZMTP_STATE_HANDSHAKE 2
#define ZMTP_STATE_HANDSHAKE_NULL_EXPECT_READY 3
#define ZMTP_STATE_HANDSHAKE_PLAIN_CLIENT_EXPECT_WELCOME 3
#define ZMTP_STATE_HANDSHAKE_PLAIN_CLIENT_EXPECT_READY 4
#define ZMTP_STATE_HANDSHAKE_PLAIN_SERVER_EXPECT_HELLO 3
#define ZMTP_STATE_HANDSHAKE_PLAIN_SERVER_VALIDATE_CREDENTIALS 4
#define ZMTP_STATE_HANDSHAKE_PLAIN_SERVER_EXPECT_INITIATE 5
#define ZMTP_STATE_HANDSHAKE_CURVE_SERVER_EXPECT_HELLO 3
#define ZMTP_STATE_HANDSHAKE_CURVE_SERVER_EXPECT_INITIATE 4
#define ZMTP_STATE_HANDSHAKE_CURVE_SERVER_VALIDATE_CLIENT_PERSISTENT_KEY 5
#define ZMTP_STATE_OPERATING 10
#define ZMTP_STATE_ERROR 254

#define E_EOF -1
#define E_INDEX_ERROR -2
#define E_BUFFER_INSUFFICIENT -3
#define E_UNREACHABLE -4
#define E_INCOMPATIBLE_SOCKET_TYPES -5
#define E_ERROR_COMMAND -6
#define E_UNEXPECTED -7
#define E_DIFFERENT_MECHANISMS -8
#define E_BAD_ROLES -9
#define E_BAD_SIGNATURE -10
#define E_BAD_CURVE_VERSION -12
#define E_BAD_CURVE_HELLO -13
#define E_CURVE_DECRYPTION_ERROR -14
#define E_CURVE_ENCRYPTION_ERROR -15
#define E_CURVE_BAD_NONCE -16
#define E_CRUVE_INITIATE_TIMEOUT -17
#define E_BAD_CURVE_VOUCH -18
#define E_CURVE_DISABLED -26
#define ZMTP_OK 0

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* SRC_ZMTP_ZMTP_STATES_H_ */
